
package com.hoodedfalcon.model;

public enum AlertMessage
{
    NO_SPACE,
    CONNECTION_REFUSED,
    UNKNOWN_HOST,
    READ_ONLY_MODE,
    EMPTY_DATABASE,
    EMPTY_DATABASE_ROM,
    NO_PREVIOUS_RECORDS,
    NO_ADDITIONAL_RECORDS,
    CONNECTION_OVERRIDING,
    DISCONNECT_UNSAVED_RECORDS,
    CLOSE_UNSAVED_RECORDS,
    LOAD_UNSAVED_RECORDS,
    SERVER_ERROR,
    SERVER_ERROR_UPDATING
}
